package com.qkun.wanandroid_java.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qkun.wanandroid_java.db.HistoryModel;

import com.qkun.wanandroid_java.dao.HistoryModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyModelDaoConfig;

    private final HistoryModelDao historyModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyModelDaoConfig = daoConfigMap.get(HistoryModelDao.class).clone();
        historyModelDaoConfig.initIdentityScope(type);

        historyModelDao = new HistoryModelDao(historyModelDaoConfig, this);

        registerDao(HistoryModel.class, historyModelDao);
    }
    
    public void clear() {
        historyModelDaoConfig.clearIdentityScope();
    }

    public HistoryModelDao getHistoryModelDao() {
        return historyModelDao;
    }

}
